[project]
name = "dados-hospitalares"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "matplotlib>=3.10.9",
    "nest-asyncio>=1.6.0",
    "oci>=2.185.0",
    "oracledb>=4.0.2",
    "pandas>=2.3.3",
    "pathlib>=1.0.1",
    "plotly>=7.0.0",
    "pysus>=2.3.0",
    "requests>=2.34.2",
    "streamlit>=1.62.0",
]
